#!/bin/bash
######################################################
## THIS SCRIPT CREATES NESTED FOLDERS IN THE PWD
## TAKING THE FOLDERNAMES FROM FOLDERNAMES.TXT
## CREATED BY: ABHISHEK PALIWAL
## FIRST CREATED ON: Friday March 10, 2017
## LAST MODIFIED ON: Friday March 10, 2017
######################################################
echo #Blank line
echo '======================================'
echo 'CHECK CAREFULLY: Make sure you sure you want to create folders in this directory:'
pwd ##check the present working directory
echo '======================================'
echo #Blank line

echo '======================================'
echo "Enter Prefix for BRAND NAME in lowercase, with no spaces : [e.g. = concepro OR mggk]"
echo '======================================'
read brandNamePrefix
## Converting to LowerCase just in case
brandNamePrefix=`echo $brandNamePrefix | tr '[:upper:]' '[:lower:]'`


## DEFINING SOME VARIABLES (IMPORTANT: NO SPACES before = sign)
TMP_FOLDER_LOGFILE="_README_AUTOGENERATED_with_prefix_$brandNamePrefix.txt" ;

## SAVING ALL FOLDER-NAMES TO BE CREATED TO A TMP FILE
## ADD MORE HERE IF YOU DESIRE
cat > $TMP_FOLDER_LOGFILE <<- EOM
$brandNamePrefix-00-free-stock-photos
$brandNamePrefix-====
$brandNamePrefix-00-external-communication
$brandNamePrefix-====
$brandNamePrefix-01-cta
$brandNamePrefix-01-cta/blog
$brandNamePrefix-01-cta/email
$brandNamePrefix-01-cta/landing-ty
$brandNamePrefix-01-cta/landing-ty/tofu
$brandNamePrefix-01-cta/landing-ty/mofu
$brandNamePrefix-01-cta/pages
$brandNamePrefix-====
$brandNamePrefix-02-email
$brandNamePrefix-02-email/weekly
$brandNamePrefix-02-email/monthly
$brandNamePrefix-====
$brandNamePrefix-03-identity
$brandNamePrefix-03-identity/favicons
$brandNamePrefix-03-identity/fonts
$brandNamePrefix-03-identity/logos
$brandNamePrefix-====
$brandNamePrefix-04-images
$brandNamePrefix-04-images/archived-images
$brandNamePrefix-04-images/blog
$brandNamePrefix-04-images/icons
$brandNamePrefix-04-images/landing-ty
$brandNamePrefix-04-images/pages
$brandNamePrefix-04-images/products
$brandNamePrefix-04-images/screenshots
$brandNamePrefix-04-images/team
$brandNamePrefix-====
$brandNamePrefix-05-offers
$brandNamePrefix-05-offers/blog
$brandNamePrefix-05-offers/pages
$brandNamePrefix-05-offers/webinars
$brandNamePrefix-====
$brandNamePrefix-06-resources
$brandNamePrefix-====
$brandNamePrefix-07-scripts
$brandNamePrefix-====
$brandNamePrefix-08-social
$brandNamePrefix-08-social/profiles
$brandNamePrefix-08-social/sharing
$brandNamePrefix-====
$brandNamePrefix-09-video
EOM

## CREATING FOLDERS USING MKDIR
mkdir `cat $TMP_FOLDER_LOGFILE`

## DELETING UNNECESSARY FOLDER
rm -rf $brandNamePrefix-====


## WRITING SOME LOG STUFF TO README FILE
echo '###########################################' >> $TMP_FOLDER_LOGFILE
echo "## ALL OF THE ABOVE FOLDERS CREATED: " >> $TMP_FOLDER_LOGFILE
echo "## IN `pwd`" >> $TMP_FOLDER_LOGFILE
echo "## ON `date`" >> $TMP_FOLDER_LOGFILE
echo '###########################################' >> $TMP_FOLDER_LOGFILE

## APPENDING FILE NAMING CONVENTIONS AND RULES TO THE TMP FILE
cat >> $TMP_FOLDER_LOGFILE <<- EOM
      ============== ////// ===============
      ============== ////// ===============
      ## File Naming Rules
      This is also good for search-engine-optimized URLs.
      The most optimized method for naming files (videos, images, content offers, etc.) is:
      ============== ////// ===============
      - Use lowercase letters only
      - Keep the file names short (Three-to-four words at the most)
      - Use hyphens to break between words (Rather than spaces, use hyphens)
      - Use some keywords (What's the image about? Pick one or two keywords related to the displayed image)
      ============== ////// ===============
      ## File Structure
      - Free Stock Photos (For: Images downloaded from the web)
      - cta (For: Call to Action images and related assets)
      - email (For: Email assets)
      - identity (For: Logos, fonts and other resources directly related to your brand)
      - images (For: Just about every image used on the site ; archived-images For: old ones we don't use, but might have a need for)
      - offers (For: Content offers)
      - resources (For: Internal resources for our team)
      - scripts (For: Javascript files)
      - social (For: Images directly related to social sharing)
      - video (For: Videos utilized on the site)
      ============== ////// ===============
      ## Nomenclature
      - LP : Landing page
      - TY : Thank you page
      - TOFU : Top of funnel
      - MOFU : Middle of funnel
      ============== ////// ===============
      ============== ////// ===============
EOM

## OPENING directory (Valid only on Macs)
open ./
