#!/bin/bash
THIS_SCRIPT_NAME="$(basename $0)" ;
THIS_SCRIPT_NAME_SANS_EXTENSION="$(echo $THIS_SCRIPT_NAME | sed 's/\.sh//g')" ;

##++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
## CREATING SCRIPT USAGE FUNCION AND CALLING IT VIA '--help'
usage()
{
cat <<EOM
USAGE: $(basename $0)
    ################################################################################
    ## FILENAME = $THIS_SCRIPT_NAME
    ## USAGE:
    #### > bash $THIS_SCRIPT_NAME
    ################################################################################
    ## REQUIREMENTS :
    #### FILE = Requires one or more text file(s) (*.txt) to be present in PWD.
    ################################################################################
    ## THIS FILE GETS THE URLs VALUES FROM ALL MD FILES IN A DIRECTORY ENTERED AS USER INPUT,
    ## AND SAVES THEM IN A TEXT FILE IN PWD. IF THE DIRECTORY IS NOT SPECIFIED THEN, 
    ## THIS FILE READS ALL TEXT FILES PRESENT IN PWD AND OUTPUTS AN HTML FILE FOR
    ## EACH TEXT FILE READ. 
    ## THIS PROGRAM CONVERTS EACH LINE IN THOSE TEXT FILES TO CORRESPONDING HYPERLINKS.
    ################################################################################
    ######### STRUCTURE OF required text file ##############################
    #### ...
    #### ...
    #### http://localhost:1313/white-sauce-pasta-recipe/
    #### http://localhost:1313/5-bean-curry-recipe/
    #### http://localhost:1313/halwa-chana-poori-ashtami-prashad-video-recipe/
    #### ...
    #### ...
    ################################################################################
    ## CREATED BY: PALI
    ## CREATED ON: OCT 25, 2020
    ################################################################################
EOM

exit 0 ## EXITING IF ONLY USAGE IS NEEDED
}
## Calling the usage function
if [ "$1" == "--help" ] ; then usage ; fi
##++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

##################################################################################
WORKING_DIR="$HOME_WINDOWS/Desktop/Y" ;
PWD=$(pwd);
echo;
echo "## PRESENT WORKING DIRECTORY = $PWD" ;
################################################################################
## USER INPUT:
echo; 
echo ">>>> ENTER THE FULL PATH OF THE DIRECTORY TO USE FOR READING MARKDOWN FILES (press ENTER key for default) =>" ;
read DIR_FOR_URL_EXTRACTION
echo;
## Actual url extraction and saving to a txt file in PWD
grep -irh 'url:' "$DIR_FOR_URL_EXTRACTION"/* | sort | tr -d ' ' | sed 's+url:+http://localhost:1313+g' > $WORKING_DIR/$(basename $DIR_FOR_URL_EXTRACTION.txt)

################################################################################
echo; 
echo "#### TEXT FILES WILL BE READ FROM THIS DIRECTORY = $PWD" ;
echo "#### HTML OUTPUTS WILL BE CREATED IN THIS DIRECTORY = $WORKING_DIR" ;
echo;
echo "#### Following *.txt files are found, and will be used ..." ;
ls -1 $WORKING_DIR/*.txt | nl
echo;
################################################################################

##------------------------------------------------------------------------------
function FUNCTION_CONVERT_TEXT_LINES_TO_HYPERLINKS () {
  input_file="$1" ; ## Get the argument text file from command line
  input_file_basename="$(basename $input_file)" ;
  input_file_basename_sans_extension="$(echo $input_file_basename | sed 's/\.txt//g' )" ;

  OUTPUT_HTMLFILE="$WORKING_DIR/_TMP_OUTPUT_$THIS_SCRIPT_NAME_SANS_EXTENSION-$input_file_basename_sans_extension.html" ;
  ## Writing first line to output html file
  echo "<h1>List of all Lines converted to URLs</h1>" > $OUTPUT_HTMLFILE ;
  echo "<h2>(found in file => $input_file)</h2>" >> $OUTPUT_HTMLFILE ;
  echo "<p>File autogenerated at: $(date)</p>" >> $OUTPUT_HTMLFILE ;
  echo "<p>File autogenerated by this script: $THIS_SCRIPT_NAME</p><hr>" >> $OUTPUT_HTMLFILE ;
  ####################################
  ## Looping through all lines found in input text file
  count=1 ;
  while IFS= read -r line
  do
    line_cleaned=$(echo $line | sed 's+http://localhost:1313/++g') ;
    echo "<h3>$count. <a target='_blank' href='$line'>$line_cleaned</a></h3>(Original link = $line)" >> $OUTPUT_HTMLFILE ;
  ((count++)) ;  
  done < "$input_file" 
  ####################################
  echo ">> OUTPUT HTML FILE CREATED AS: $OUTPUT_HTMLFILE" ;
  echo; 
}
##------------------------------------------------------------------------------

## Running this function over all *.txt files found in PWD
for txtFile in $(ls $PWD/*.txt) ; do
  echo ">> CURRENT TEXT FILE READING => $txtFile"
  FUNCTION_CONVERT_TEXT_LINES_TO_HYPERLINKS "$txtFile" ;
done 

