#!/bin/bash

HUGODIR="$DIR_GITHUB/2019-HUGO-MGGK-WEBSITE-OFFICIAL/content" ; 
WORKDIR="$HOME_WINDOWS/Desktop/Y" ;
FILE1=$(basename $(find $WORKDIR/ -type f -name "*.txt" | head -1)) ;
FILE2="$WORKDIR/_tmp_urls.txt" ;

FILE_FINAL="$WORKDIR/_tmp_FINAL.html" ;
## writing first line
echo "<h1>Finding maching urls with the words in the given text file</h1>" > $FILE_FINAL
echo "File autogenerated at: $(date)" >> $FILE_FINAL
#echo "<pre>" >> $FILE_FINAL ;

## Removing extra character and also converting to lowercase
cat $FILE1 | awk '{print tolower($0)}' | tr ' ' '\n' | sed 's/"//g' | sed 's/\.//g' | sed 's/,//g' | sed "s+\'++g" | sed 's/-/ /g' | tr -d ' ' | sort | uniq > _tmp_$FILE1

##
#grep -irh 'url: ' $HUGODIR/ | sed 's/url: //g' | sed 's+/++g' | sed 's/-/ /g' > $HOME/Desktop/Y/_tmp1.txt
grep -irh 'url: ' $HUGODIR/ | sed 's/url: //g'  > $FILE2 ;

####################################################
function FUNCTION_FIND_COMMON_WORDS_IN_URLS () {
    file_input=$1; 
    file_with_urls=$2 ;
    file_tmp="$WORKDIR/_tmp0.txt"
    
    COUNT=0;
    while read WORD;
    do
    ####
        WORD=$(echo "$WORD"| cut -d" " -f 1);  ## Separating words by spaces      
        grep "$WORD" $file_with_urls > $file_tmp ;
        lines_matched=$(cat $file_tmp | wc -l | tr -d ' ') ;
        ## Register matches if 1 <= matches <= 5, because too many ...
        ## matches mean general words are being matched.
        if [ $lines_matched -le 200 ] && [ $lines_matched -ge 1 ]  ; then
            ((COUNT++)) 
            echo >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            echo "<h2>$COUNT // $WORD</h2>" >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            cat $file_tmp | sed 's/^/<br>/g' | sed "s+$WORD+<span style='color:red;'>$WORD</span>+g" >> $FILE_FINAL ;
        fi
    ####    
    done < $file_input
}
## RUN THIS FUNCTION
FUNCTION_FIND_COMMON_WORDS_IN_URLS _tmp_$FILE1 $FILE2
#echo "</pre>" >> $FILE_FINAL ;

################################################################################ 
## SUMMARY PRINTING
echo; 
echo "FILE1 = $FILE1" ;
echo "FILE2 = $FILE2" ;
################################################################################
