#!/bin/bash

HUGODIR="$REPO_MGGK/content" ; 
FILE_WITH_WORDS_TO_DISCARD="$REPO_SCRIPTS_MGGK/_REQUIREMENT_FILES_MGGK/999A-MGGK-WORDS-TO-DISCARD.txt" ;
WORKDIR="$DIR_Y" ;
FILE1=$(basename $(find $WORKDIR/ -type f -name "*.txt" | head -1)) ;
FILE2A="$WORKDIR/_tmp_urls0.txt" ;
FILE2="$WORKDIR/_tmp_urls1.txt" ;
FILE3="$WORKDIR/_tmp_ALL_URLS.txt" ;


FILE_FINAL="$WORKDIR/_tmp_FINAL.html" ;
## writing first line
echo "<h1>Finding maching urls with the words in the given text file</h1>" > $FILE_FINAL
echo "File autogenerated at: $(date)" >> $FILE_FINAL

## Removing extra character and also converting to lowercase
#cat $FILE1 | awk '{print tolower($0)}' | tr ' ' '\n' | sed 's/"//g' | sed 's/\.//g' | sed 's/,//g' | sed "s+\'++g" | sed 's/-/ /g' | tr -d ' ' | sort | uniq > _tmp_$FILE1

##
grep -irh 'url: ' $HUGODIR/ | sed 's/url: //g' | sed 's+/++g' | sed 's/-/ /g' | tr ' ' '\n' | sed 's/"//g' |sort | uniq > $FILE2A ;

##
grep -irh 'url: ' $HUGODIR/ | sed 's+url: +https://www.mygingergarlickitchen.com+g'  > $FILE3 ;

##
comm -13 $FILE_WITH_WORDS_TO_DISCARD $FILE2A > $FILE2

####################################################
function FUNCTION_FIND_COMMON_WORDS_IN_URLS () {
    file_input=$1; 
    file_with_urls=$2 ;
    file_tmp0="$WORKDIR/_tmp0.txt"
    file_tmp1="$WORKDIR/_tmp1.txt"
    
    COUNT=0;
    while read WORD;
    do
    ####
        WORD=$(echo "$WORD"| cut -d" " -f 1);  ## Separating words by spaces      
        grep -i "$WORD" $file_with_urls > $file_tmp0 ;
        grep -i "$WORD" $FILE3 > $file_tmp1 ;
        lines_matched=$(cat $file_tmp0 | wc -l | tr -d ' ') ;
        ## Register matches if 1 <= matches <= 5, because too many ...
        ## matches mean general words are being matched.
        if [ $lines_matched -le 200 ] && [ $lines_matched -ge 1 ]  ; then
            ((COUNT++)) 
            echo >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            echo "<h2>$COUNT // $WORD</h2>" >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            cat $file_tmp1 | sed 's/^/<br>/g' | sed "s+$WORD+<span style='color:blue;'>$WORD</span>+g" >> $FILE_FINAL ;
            echo "<br><br>" >> $FILE_FINAL ;
            cat $file_tmp0 | sed 's/^/<br>/g' | sed "s+$WORD+<span style='color:red;'>$WORD</span>+g" >> $FILE_FINAL ;
        fi
    ####    
    done < $file_input
}
## RUN THIS FUNCTION
FUNCTION_FIND_COMMON_WORDS_IN_URLS $FILE2 $FILE1 

################################################################################ 
## SUMMARY PRINTING
echo; 
echo "FILE1 = $FILE1" ;
echo "FILE2 = $FILE2" ;
################################################################################
