#!/bin/bash
##################################################################################
THIS_SCRIPT_NAME="$(basename $0)" ;
THIS_SCRIPT_NAME_SANS_EXTENSION="$(echo $THIS_SCRIPT_NAME | sed 's/\.sh//g')" ;
##
WORKDIR="$DIR_Y" ;
cd $WORKDIR ; echo ">>>> Current working directory => $WORKDIR" ;
##################################################################################

##++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
## CREATING SCRIPT USAGE FUNCION AND CALLING IT VIA '--help'
usage()
{
cat <<EOM
USAGE: $(basename $0)
    ################################################################################
    ## THIS SCRIPT TAKES THE FIRST TEXT FILE WITH RECIPE WRITE UP, WHICH IS PRESENT IN
    ## CURRENT WORKING DIRECTORY ( = $WORKDIR ) AND MATCHES ITS WORDS
    ## WITH THE EXISTING URLS PRESENT ON MGGK WEBSITE THE SAME WAY WORDPRESS SUGGESTS
    ## EXISTING URLS FOR MATCHED WORDS.
    ## FINALLY IT PRODUCES AN OUTPUT HTML FILE WITH MATCHED WORDS AND LINKS.
    ################################################################################
    ## REQUIREMENT: 
    ## Make sure to rename your text file with prefix 'recipe' ...
    ## ... in the format => recipe-ANY_FILENAME.txt
    ## SCRIPT USES: GNU sed Utility => gsed (get it thru homebrew)
    ######
    ## ALSO, THIS FILE IS REQUIRED:
    ## FILE_WITH_WORDS_TO_DISCARD="$REPO_SCRIPTS_MGGK/_REQUIREMENT_FILES_MGGK/999A-MGGK-WORDS-TO-DISCARD.txt" ;
    ################################################################################
    ## CREATED BY: PALI
    ## CREATED ON: NOV 05, 2020
    ################################################################################
EOM

exit 0 ## EXITING IF ONLY USAGE IS NEEDED
}
## Calling the usage function
if [ "$1" == "--help" ] ; then usage ; fi
##++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

##################################################################################
HUGODIR="$REPO_MGGK/content" ; 
FILE_WITH_WORDS_TO_DISCARD="$REPO_SCRIPTS_MGGK/_REQUIREMENT_FILES_MGGK/999A-MGGK-WORDS-TO-DISCARD.txt" ;

echo "################################################################################"
echo "## IMPORTANT REQUIREMENT: Make sure to rename your text file with prefix 'recipe' in the format => recipe-ANY_FILENAME.txt"
echo "################################################################################"

FILE1=$(basename $(find $WORKDIR/ -type f -name "recipe*.txt" | head -1)) ;
echo; echo ">> THIS TEXT FILE WILL BE USED FOR RECIPE WRITEUP = $FILE1" ; echo;
echo ">> Currently looking for words to match with URLs ... wait for some seconds ..." ;
echo; 

FILE2A="$WORKDIR/_tmp_urls0.txt" ;
FILE2="$WORKDIR/_tmp_urls1.txt" ;
FILE3="$WORKDIR/_tmp_ALL_URLS.txt" ;
##
FILE_FINAL="$WORKDIR/_OUTPUT-$THIS_SCRIPT_NAME_SANS_EXTENSION.html" ;

## writing first line to final output html file
echo "<!doctype html>
<html lang='en'>
  <head>
    <!-- Required meta tags -->
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <!-- Bootstrap CSS -->
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css' integrity='sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2' crossorigin='anonymous'>
    <title>OUTPUT - $THIS_SCRIPT_NAME_SANS_EXTENSION</title>
  </head>
  <body><div class='container'>" > $FILE_FINAL

echo "<div class='jumbotron jumbotron'>
<h1>MGGK: Finding matching Post Titles + URLs with the words in the given text file (=> $FILE1)</h1>
<p>File autogenerated by script: $THIS_SCRIPT_NAME<br>File autogenerated at: $(date)</p>
</div>" >> $FILE_FINAL


## Removing extra character and also converting to lowercase
grep -irh '^title: ' $HUGODIR/ | awk '{print tolower($0)}' | sed 's/title: //g' | sed 's+/++g' | sed 's/-/ /g' | sed 's/"//g' | sed "s/'//g" | sed 's/\.//g' | sed 's/(//g' | sed 's/)//g' | sed 's/\[//g' | sed 's/\]//g' | sed 's/,//g' | sed 's/\?//g' | sed 's/|//' | sed 's/–//g' | sed 's/—//g' |sed 's/!//g'| sed 's/+//g' | tr ' ' '\n'  | grep -v '^$' | sort | uniq > $FILE2A ;

##
echo "" > $FILE3 ;
for mdfile in $(grep -irl 'url: ' $HUGODIR/) ; do
  mytitle=$(grep -irh '^title: ' $mdfile | sed 's+title: ++g' | awk '{print tolower($0)}' | sed 's/"//g') ;
  myurl=$(grep -irh '^url: ' $mdfile | sed 's+url: +https://www.mygingergarlickitchen.com+g') ;
  ##
  #echo "$mytitle ====> ( $myurl )" >> $FILE3 ;
  echo "<a target='_blank' href='$myurl'>$mytitle</a>" >> $FILE3 ;
done 

##
comm -13 $FILE_WITH_WORDS_TO_DISCARD $FILE2A > $FILE2

####################################################
function FUNCTION_FIND_COMMON_WORDS_IN_URLS () {
    ##
    file_input=$1; 
    file_with_urls=$2 ;
    file_tmp0="$WORKDIR/_tmp0.txt"
    file_tmp1="$WORKDIR/_tmp1.txt"
    
    COUNT=0;
    while read WORD;
    do
    ####
        WORD=$(echo "$WORD"| cut -d" " -f 1);  ## Separating words by spaces      
        grep -iw "$WORD" $file_with_urls > $file_tmp0 ;
        grep -iw "$WORD" $FILE3 > $file_tmp1 ;
        lines_matched=$(cat $file_tmp0 | wc -l | tr -d ' ') ;
        ## Register matches if 1 <= matches <= 200, because too many ...
        ## matches mean general words are being matched.
        if [ $lines_matched -le 200 ] && [ $lines_matched -ge 1 ]  ; then
            ((COUNT++)) 
            echo >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            echo "<h2>$COUNT // $WORD</h2>" >> $FILE_FINAL ;
            echo "<hr>" >> $FILE_FINAL ;
            ##
            echo; echo "... found a matching word ... $COUNT // $WORD" ; echo;

            #### Begin: collapsible bootstrap element   
            echo "<p>MATCHED TEXT LINES: <button class='btn btn-primary' type='button' data-toggle='collapse' data-target='#collapse_$WORD' aria-expanded='false' aria-controls='#collapse_$WORD'>Click to show all lines containing this word => $WORD</button></p>" >> $FILE_FINAL ;
            echo "<div class='collapse' id='collapse_$WORD'><div class='card card-body'><p>"  >> $FILE_FINAL ;
            ##------
            cat $file_tmp0 | gsed 's+^+<br><br>// +g' | gsed "s+$WORD+<span style='color:red;'><strong>$WORD</strong></span>+g" >> $FILE_FINAL ;
            ##------  
            echo "</p></div></div>" >> $FILE_FINAL ;
            #### End: collapsible bootstrap element   

            echo "<strong>MATCHED POST TITLES (lowercase) WITH THEIR URLS:</strong>" >> $FILE_FINAL ;
            #cat $file_tmp1 | sed 's+^+<br><br>// +g' | sed "s+$WORD+<span style='color:blue;'><strong>$WORD</strong></span>+g" >> $FILE_FINAL ;
            cat $file_tmp1 | sed 's+^+<br><br>\&bull; +g' >> $FILE_FINAL ;
        fi
    ####    
    done < $file_input
}
## RUN THIS FUNCTION
FUNCTION_FIND_COMMON_WORDS_IN_URLS $FILE2 $FILE1 

##################################################################################
echo "   <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src='https://code.jquery.com/jquery-3.5.1.slim.min.js' integrity='sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj' crossorigin='anonymous'></script>
    <script src='https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js' integrity='sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx' crossorigin='anonymous'></script>  
  </div></body>
</html>" >> $FILE_FINAL


################################################################################ 
## SUMMARY
echo; 
echo "## SUMMARY ..." ;
echo; 
echo "  FILE1 = $FILE1" ;
echo "  FILE2 = $FILE2" ;
echo "  FILE2A = $FILE2A" ;
echo "  FILE2 = $FILE2" ;
echo "  FILE3 = $FILE3" ;
echo "  CREATED // OUTPUT HTML FILE => $FILE_FINAL" ;
## OPEN OUTPUT FILE IN BROWSER
open $FILE_FINAL ;
################################################################################
